name: Build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: containerbase/internal-tools/setup@13682cd9a4824f96814c0b3ca545f0adaefdb202 # v3.10.2
        with:
          save-cache: true
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm eslint

      - run: pnpm prettier

  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22

    steps:
      - uses: containerbase/internal-tools/setup@13682cd9a4824f96814c0b3ca545f0adaefdb202 # v3.10.2
        with:
          save-cache: true
          node-version: ${{ matrix.node-version }}
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm test:unit

      - run: pnpm test:integration

  # Catch-all required check for test matrix
  success:
    needs:
      - lint
      - test
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or cancelled lint tests
        if: |
          needs.lint.result == 'failure' ||
          needs.lint.result == 'cancelled'
        run: exit 1

      - name: Fail for failed or cancelled test tests
        if: |
          needs.test.result == 'failure' ||
          needs.test.result == 'skipped'
        run: exit 1
