name: Build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: containerbase/internal-tools/setup@9d974fd61a2b37c198fac584cc8b32e8585213b7 # v3.10.1
        with:
          save-cache: true
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm test
