name: Build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: containerbase/internal-tools/setup@d005037f4b778e5c456510a397b91f8ac19078e6 # v3.9.0
        with:
          save-cache: true
          pnpm-cache: |
            node_modules
            package/*/node_modules

      - run: pnpm build

      - run: pnpm test
