name: Upload Database

on:
  schedule:
    - cron: '0 5,17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: containerbase/internal-tools/setup@d005037f4b778e5c456510a397b91f8ac19078e6 # v3.9.0
        with:
          pnpm-cache: |
            node_modules
            packages/*/node_modules

      - run: pnpm build

      - run: pnpm start
        env:
          GITHUB_TOKEN: ${{ github.token }}
